# Generated by Django 5.1.7 on 2025-03-16 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the category.', max_length=20, verbose_name='Category Title')),
                ('parent', models.ForeignKey(blank=True, help_text='Select a parent category (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
