# Generated by Django 5.1.7 on 2025-03-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of Product', max_length=20, verbose_name='product Title')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the price of product', max_digits=4, verbose_name='Product')),
                ('price_discount', models.DecimalField(decimal_places=2, default=0.0, help_text="Enter the dicsount of product's price", max_digits=4, verbose_name="discount of product's price")),
                ('final_price_value', models.DecimalField(decimal_places=2, default=0.0, help_text='The final price after applying the discount.', max_digits=5, verbose_name='Final Price')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Enter the number of items in stock.', verbose_name="product's stock")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upadate at')),
                ('category', models.ManyToManyField(help_text='Select a category for product', to='product.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
