# Generated by Django 5.1.7 on 2025-03-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Select the option values for this group.', max_length=40, unique=True, verbose_name='Option group title')),
            ],
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Enter the specific value for this option (e.g., "Red", "Large").', max_length=30, verbose_name='Option Value')),
                ('option_group', models.ForeignKey(help_text='Select the option group to which this value belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='product.optiongroup', verbose_name='Option Group')),
            ],
        ),
    ]
