# Generated by Django 5.1.7 on 2025-03-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_optiongroup_optionvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_group_attribiute', to='product.optiongroup')),
                ('proudct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='product.product')),
            ],
        ),
    ]
