# Generated by Django 5.1.7 on 2025-03-29 12:01

import django.db.models.deletion
import django.utils.timezone
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=product.models.product_image_path, verbose_name='Image File'),
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('index',), 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='index',
            field=models.PositiveIntegerField(default=0, help_text='Determines sorting order in image galleries (lower numbers show first)', verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this image should be displayed publicly', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product', verbose_name='Product'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
