# Generated by Django 5.1.7 on 2025-03-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productimage_image_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_active',
        ),
    ]
