# Generated by Django 5.1.7 on 2025-05-10 13:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productimage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the option attribute.', max_length=50, verbose_name='Option Attribute Title')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
            },
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='option_group',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='proudct',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='optiongroup',
            options={'ordering': ['title'], 'verbose_name': 'Option group', 'verbose_name_plural': 'Option groups'},
        ),
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'ordering': ['value'], 'verbose_name': 'Option Value', 'verbose_name_plural': 'Option Values'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the category'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls whether the category is visible in the storefront'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title', unique=True),
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the option group'),
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls whether the option group is available'),
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls whether the option value is available'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls whether the product is visible in the storefront'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select a parent category (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.category', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Enter the title of the category.', max_length=50, unique=True, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(help_text='Select categories for product', related_name='products', to='product.category', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The final price after applying the discount.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Final Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the price of product', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Enter the discount percentage of product's price", max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Enter the number of items in stock.', verbose_name='Product Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Enter the title of Product', max_length=100, verbose_name='Product Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterUniqueTogether(
            name='optionvalue',
            unique_together={('value', 'option_group')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='product_cat_slug_93e2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='product_cat_parent__b54811_idx'),
        ),
        migrations.AddIndex(
            model_name='optiongroup',
            index=models.Index(fields=['is_active'], name='product_opt_is_acti_43b624_idx'),
        ),
        migrations.AddIndex(
            model_name='optionvalue',
            index=models.Index(fields=['is_active'], name='product_opt_is_acti_23070c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_pro_slug_33a021_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='product_pro_is_acti_9d034c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='product_pro_created_57e07a_idx'),
        ),
        migrations.AddField(
            model_name='optionattribute',
            name='option_group',
            field=models.ForeignKey(help_text='Select the option group this attribute belongs to.', on_delete=django.db.models.deletion.CASCADE, to='product.optiongroup', verbose_name='Option Group'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='option_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value', to='product.optionvalue', verbose_name='Option Value'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_values', to='product.product'),
        ),
        migrations.AddField(
            model_name='productoptiongroup',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_group_attribute', to='product.optiongroup'),
        ),
        migrations.AddField(
            model_name='productoptiongroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='product.product'),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
